import json
import logging
import os
import re

from fastapi import APIRouter, Depends, HTTPException
from google import genai
from sqlalchemy.orm import Session

from app.auth import get_current_user
from app.database import get_db
from app.models import Course, Question, User
from app.schemas import CourseCreateRequest, CourseOut, CourseUpdateRequest
from app.services.course_loader import create_course, delete_course, edit_course
from app.services import supermemory_service as sm

log = logging.getLogger(__name__)


def _all_topics(course: Course, db: Session) -> list[str]:
    """Merge stored course topics with topics from existing questions."""
    stored = set(course.topics)
    question_topics = (
        db.query(Question.topic)
        .filter(Question.course_id == course.id, Question.topic != "")
        .distinct()
        .all()
    )
    stored.update(t[0] for t in question_topics)
    return sorted(stored)

router = APIRouter(prefix="/courses", tags=["courses"])

@router.get("/", response_model=list[CourseOut])
def list_courses(db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    return db.query(Course).filter(Course.user_id == user.id).all()


@router.get("/graph/all")
def get_knowledge_graph(
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    """Fetch the supermemory knowledge graph for all of a user's courses.

    Includes both course-level document memories (container_tag = course slug)
    and user-specific learning memories (container_tag = user_{id}_course_{id}).
    """
    courses = db.query(Course).filter(Course.user_id == user.id).all()
    empty = {"documents": [], "pagination": {"currentPage": 1, "limit": 300, "totalItems": 0, "totalPages": 0}}
    if not courses:
        return empty

    container_tags: list[str] = []
    for c in courses:
        if c.container_tag:
            container_tags.append(c.container_tag)
        container_tags.append(f"user_{user.id}_course_{c.id}")

    try:
        return sm.get_graph_data(container_tags, limit=300)
    except Exception:
        log.exception("Failed to fetch knowledge graph for user %s", user.id)
        return empty


@router.get("/{course_id}", response_model=CourseOut)
def get_course(course_id: int, db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    course = db.query(Course).filter(Course.id == course_id, Course.user_id == user.id).first()
    if not course:
        raise HTTPException(status_code=404, detail="Course not found")
    # Merge stored topics with topics from existing questions
    course.topics = _all_topics(course, db)
    return course

@router.post("/", response_model=CourseOut)
def create_course_endpoint(
    req: CourseCreateRequest,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    title_text = req.title.strip()
    if not title_text:
        raise HTTPException(status_code=400, detail="Title cannot be empty")
    
    # 1. Auto-generate the slug for container_tag and path
    # Removes special chars, replaces spaces with hyphens
    slug = re.sub(r'\W+', '-', title_text.lower()).strip('-')

    try:
        # 2. Call service (Mapping title_text to 'name' in your DB)
        course = create_course(db, title_text, user.id)
        
        # 3. Manually set the autogenerated fields
        course.container_tag = slug
        course.path = f"/courses/{slug}"
        
        db.commit()
        db.refresh(course)
        return course
    except Exception as e:
        print(f"Error creating course: {e}")
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/{course_id}/topics", response_model=list[str])
def get_topics(course_id: int, db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    course = db.query(Course).filter(Course.id == course_id, Course.user_id == user.id).first()
    if not course:
        raise HTTPException(status_code=404, detail="Course not found")
    return _all_topics(course, db)


_INSIGHTS_PROMPT = """\
You are analyzing a student's learning data for a course. Below is raw data \
from their learning history. Produce a clean JSON summary.

Rules:
- Write in SECOND PERSON ("You", not "Student" or "The student")
- Keep each bullet concise (one sentence max)
- Strengths = topics/skills they consistently get right or understand well
- Weaknesses = topics/skills they struggle with, get wrong, or need practice on
- Only include items clearly supported by the data. Do not invent or guess.
- If a memory says "Student answered correctly on topic X" that's a strength.
- If a memory says "Student answered incorrectly on topic X" that's a weakness.
- Deduplicate: if multiple memories say the same thing, combine into one bullet.
- Recent activity = what they've been working on lately (from dynamic profile)
- If there's not enough data for a section, return an empty array for it.

RAW PROFILE DATA:
Static facts: {static}
Dynamic context: {dynamic}

RAW MEMORIES:
{memories}

Return ONLY valid JSON in this exact format, no markdown fences:
{{"strengths": ["..."], "weaknesses": ["..."], "recent_activity": ["..."]}}
"""


def _process_insights_with_gemini(raw: dict) -> dict:
    """Use Gemini to clean and categorize raw supermemory data."""
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        log.warning("GEMINI_API_KEY not set, returning raw profile")
        return {
            "strengths": [],
            "weaknesses": [],
            "recent_activity": raw.get("dynamic", []),
        }

    static_str = "\n".join(f"- {s}" for s in raw.get("static", [])) or "(none)"
    dynamic_str = "\n".join(f"- {d}" for d in raw.get("dynamic", [])) or "(none)"
    memories_str = "\n".join(f"- {m}" for m in raw.get("memories", [])) or "(none)"

    prompt = _INSIGHTS_PROMPT.format(
        static=static_str,
        dynamic=dynamic_str,
        memories=memories_str,
    )

    try:
        client = genai.Client(api_key=api_key)
        response = client.models.generate_content(
            model="gemini-3-flash-preview",
            contents=prompt,
            config=genai.types.GenerateContentConfig(
                temperature=0.2,
                max_output_tokens=2048,
                response_mime_type="application/json",
            ),
        )
        text = response.text.strip()
        # Strip markdown fences if present
        if text.startswith("```"):
            text = re.sub(r"^```(?:json)?\s*", "", text)
            text = re.sub(r"\s*```$", "", text)
        # Check for truncation
        if (
            response.candidates
            and response.candidates[0].finish_reason
            and str(response.candidates[0].finish_reason) not in ("STOP", "FinishReason.STOP", "1")
        ):
            log.warning("Gemini insights truncated (finish_reason=%s)", response.candidates[0].finish_reason)
        log.debug("Gemini insights raw (%d chars): %s", len(text), text[:500])
        result = json.loads(text)
        return {
            "strengths": result.get("strengths", []),
            "weaknesses": result.get("weaknesses", []),
            "recent_activity": result.get("recent_activity", []),
        }
    except Exception:
        log.exception("Gemini insights processing failed")
        return {
            "strengths": [],
            "weaknesses": [],
            "recent_activity": raw.get("dynamic", []),
        }


@router.get("/{course_id}/insights")
def get_insights(course_id: int, db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    course = db.query(Course).filter(Course.id == course_id, Course.user_id == user.id).first()
    if not course:
        raise HTTPException(status_code=404, detail="Course not found")
    try:
        raw = sm.get_user_profile(user.id, course.id)
    except Exception:
        log.exception("Failed to fetch insights for course %s", course.id)
        raw = {"static": [], "dynamic": [], "memories": []}

    # If no data at all, skip Gemini call
    if not raw.get("static") and not raw.get("dynamic") and not raw.get("memories"):
        return {"strengths": [], "weaknesses": [], "recent_activity": []}

    return _process_insights_with_gemini(raw)

@router.patch("/{course_id}", response_model=CourseOut)
def update_course_endpoint(
    course_id: int,
    req: CourseUpdateRequest,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user)
):
    title_text = req.title.strip()
    if not title_text:
        raise HTTPException(status_code=400, detail="Title cannot be empty")
        
    try:
        return edit_course(db=db, course_id=course_id, user_id=user.id, new_title=title_text)
    except ValueError as e:
        # Our edit_course raises a ValueError if the course isn't found or access is denied
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        log.exception(f"Failed to update course {course_id}")
        db.rollback()
        raise HTTPException(status_code=500, detail="Internal server error")


@router.delete("/{course_id}")
def delete_course_endpoint(
    course_id: int,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user)
):
    try:
        delete_course(db=db, course_id=course_id, user_id=user.id)
        return {"ok": True}
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        log.exception(f"Failed to delete course {course_id}")
        db.rollback()
        raise HTTPException(status_code=500, detail="Internal server error")