import re
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.auth import get_current_user
from app.database import get_db
from app.models import Course, User
from app.schemas import CourseCreateRequest, CourseOut
from app.services.course_loader import create_course

router = APIRouter(prefix="/courses", tags=["courses"])

@router.get("/", response_model=list[CourseOut])
def list_courses(db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    return db.query(Course).filter(Course.user_id == user.id).all()

@router.get("/{course_id}", response_model=CourseOut)
def get_course(course_id: int, db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    course = db.query(Course).filter(Course.id == course_id, Course.user_id == user.id).first()
    if not course:
        raise HTTPException(status_code=404, detail="Course not found")
    return course

@router.post("/", response_model=CourseOut)
def create_course_endpoint(
    req: CourseCreateRequest,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
):
    title_text = req.title.strip()
    if not title_text:
        raise HTTPException(status_code=400, detail="Title cannot be empty")
    
    # 1. Auto-generate the slug for container_tag and path
    # Removes special chars, replaces spaces with hyphens
    slug = re.sub(r'\W+', '-', title_text.lower()).strip('-')

    try:
        # 2. Call service (Mapping title_text to 'name' in your DB)
        course = create_course(db, title_text, user.id)
        
        # 3. Manually set the autogenerated fields
        course.container_tag = slug
        course.path = f"/courses/{slug}"
        
        db.commit()
        db.refresh(course)
        return course
    except Exception as e:
        print(f"Error creating course: {e}")
        db.rollback()
        raise HTTPException(status_code=500, detail=str(e))